# GOAL TO FIND OUT HOW MUCH CNN IMPROVES ANN CLASSIFICAITON OF DIGITS

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [8]:
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [9]:
X_train, X_test = X_train /255, X_test /255 


# ann

In [10]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10) 

Epoch 1/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2729 - accuracy: 0.9228
Epoch 2/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1222 - accuracy: 0.9644
Epoch 3/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0844 - accuracy: 0.9750
Epoch 4/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0643 - accuracy: 0.9806
Epoch 5/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0505 - accuracy: 0.9846
Epoch 6/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0414 - accuracy: 0.9867
Epoch 7/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0334 - accuracy: 0.9898
Epoch 8/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0282 - accuracy: 0.9916
Epoch 9/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0219 - accuracy: 0.9934
Epoch 10/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.020

# for image classificaiton, They expect input in the form of (number of samples, height, width, channels),

In [14]:
X_train = X_train.reshape(-1,28,28,1)
X_train[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [15]:
X_test = X_test.reshape(-1,28,28,1)

In [17]:
model = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(100, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])


In [19]:
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [20]:
model.fit(X_train, y_train, epochs = 10)

Epoch 1/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.1565 - accuracy: 0.9536
Epoch 2/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.0529 - accuracy: 0.9840
Epoch 3/10
1875/1875 [==============================] - 18s 9ms/step - loss: 0.0355 - accuracy: 0.9891
Epoch 4/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.0238 - accuracy: 0.9922
Epoch 5/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.0164 - accuracy: 0.9947
Epoch 6/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0111 - accuracy: 0.9964
Epoch 7/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0087 - accuracy: 0.9971
Epoch 8/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0078 - accuracy: 0.9975
Epoch 9/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0051 - accuracy: 0.9984
Epoch 10/10
1875/1875 [==============================] - 15s 8ms/step - l

In [21]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0615 - accuracy: 0.9865


[0.061542585492134094, 0.9865000247955322]

In [24]:
y_hat = model.predict(X_test)
y_classes = [np.argmax(element) for element in y_hat]

313/313 [==============================] - 1s 2ms/step


In [ ]:
for i in range(len(y_classes):
    if y_classes[i] == y_