In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0]) # labels

In [2]:
one_hot("amazing restaurant",30) #creates OHE for 30 labels

[11, 13]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[25, 12], [11, 13], [18, 16], [6, 13, 23], [19, 29, 16], [5, 12], [21, 29, 1], [18, 3], [18, 24], [17, 12]]


In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[25 12  0]
 [11 13  0]
 [18 16  0]
 [ 6 13 23]
 [19 29 16]
 [ 5 12  0]
 [21 29  1]
 [18  3  0]
 [18 24  0]
 [17 12  0]]


In [11]:
embed_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embed_vector_size, input_length = max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [12]:
X = padded_reviews
y = sentiment

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 15)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [14]:
model.fit(X, y, epochs=50, verbose=0)

In [15]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 148ms/step - loss: 0.6278 - accuracy: 0.8000


0.800000011920929

In [16]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [17]:
weights[25]

array([-0.04018333,  0.01802367, -0.09734274,  0.07670979,  0.02030845],
      dtype=float32)

In [18]:
weights[11]

array([-0.05696735,  0.06737233, -0.07773312,  0.05904695,  0.09100522],
      dtype=float32)

#similar weights for similar words